export const LOGGED_IN = "LOGGED_IN"

export const LOGGED_OUT = "LOGGED_OUT"

export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST"

export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS"

export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE"