export const LOGGED_IN = "LOGGED_IN"

export const LOGGED_OUT = "LOGGED_OUT"

export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST"

export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS"

export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE"

export const CLEAR_TODO = "CLEAR_TODO"

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"

export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"